zuul:
  routes:
    tenant-service:
      path: /tenant/**
      strip-prefix: false
      service-id: tenant-service
     
      
hystrix:
  command:
    default:
    execution:
      isolation:
        thread:     
          timeoutInMillisecond:5000
          
 
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
  eager-load:
    enabled: true
    
  
 
        